---

- name: Check if project exists
  shell: "oc get project {{OCP_PROJECT}}"
  register: rhpam_result
  ignore_errors: true
  changed_when: false

- name: Create projects
  shell: "oc new-project {{OCP_PROJECT}} --display-name=\"RHPAM 7.11.0 - User {{USER_NUMBER}}\" --description=\"RHPAM 7.11 for user {{USER_NUMBER}}.\""
  when: rhpam_result is failed

- name: Annotate project namespace
  shell: "oc annotate namespace {{OCP_PROJECT}} openshift.io/requester=user{{USER_NUMBER}} --overwrite"
  when: rhpam_result is failed

- name: Make user admin
  shell: "oc policy add-role-to-user admin user{{USER_NUMBER}} -n {{OCP_PROJECT}}"
  when: rhpam_result is failed

#- name: "Configure Business Central Memory"
#  shell: "oc set env dc/rhpam7-rhpamcentr BUSINESS_CENTRAL_MEMORY_LIMIT=4Gi -n {{ OCP_PROJECT }}"
#  when: is_result is failed
